### ISSUE TITLE
Tasmota to mgos?

### ISSUE THREAD

**Issue by ashmodai6** [yaourdt/mgos-to-tasmota#14]
In the readme it mentions that there is no known way yet to come back from tasmota to the original shelly fw thru OTA but I in this conversation https://github.com/yaourdt/mgos-to-tasmota/issues/9 it seems very well be possible ?
Thanks !

**Comment by yaourdt** [comment]
Yes, have a look at https://github.com/yaourdt/tasmota-to-mgos

Apart from my own devices and @pandabear41, there is not much feedback yet, so I'd still consider it unstable software. But still I could mention this in the README.md, you are right

**Comment by yaourdt** [comment]
If you want to give it a try, please let me know if you had any issues or if the process worked as intended.

**Comment by ashmodai6** [comment]
Thanks!

**Comment by ashmodai6** [comment]
So I just successfully reverted two shelly 1 back from tasmota to the original shelly firmware without any issue. I have to go thru the extra step of upgrading to tasmota minimal as a first step but all was flawless. Thanks a lot ! I refrained to do so until now since I did want to enjoy dismantling my shellys from the wall :)

**Comment by ashmodai6** [comment]
😀 actually i did it because it was well documented in your readme !
