### ISSUE TITLE
Shelly UNI

### ISSUE THREAD

**Issue by schrej-zz** [yaourdt/mgos-to-tasmota#21]
Hi,
is there also a chance to support the Shelly UNI?
Thanks for the great work.

Joerg

**Comment by yaourdt** [comment]
Lets try: http://shellyip/ota?url=http://dl.dasker.eu/uni/firmware.zip - does that work?

**Comment by schrej-zz** [comment]
Hi Mark,
looks also very good.
Works as expected.
Thanks for your great work.
Joerg

**Comment by yaourdt** [comment]
Nice! You are very welocme!
