### ISSUE TITLE
Shelly Duo GU10 (not RGB)

### ISSUE THREAD

**Issue by BusinessClaes** [yaourdt/mgos-to-tasmota#55]
Any chance that the tasmota OTA-firmware for the Shelly Duo (E27 socket) will work also with the Shelly Duo GU10? Has anyone tried? And I mean the white-only, not the RGBW one :)

Btw why is it listed both Shelly Bulb and Shelly Duo RGBW? Are they not the same device? (not my main question, but I just wonder)

**Comment by BusinessClaes** [comment]
I look at the Shelly firmware files and I only find one entry with Duo on it, so maybe the E27 and the GU10 are the same device with different enclosures?

"SHBDUO-1":{"url":"http:\/\/shelly-api-eu.shelly.cloud\/firmware\/SHBDUO-1.zip","version":"20210909-143858\/v1.11.4-DNSfix-ge6b2f6d"}

**Comment by FerFemNemBem** [comment]
Hi,
same question here. Did onyone have tried to flash the "Duo G10" with the "DUO" Tasmota-firmware? Was it successful?
BR,
FFNB

**Comment by BusinessClaes** [comment]
I did it ant it worked, so good news! 👍
