### ISSUE TITLE
Not able to flash Shelly 1

### ISSUE THREAD

**Issue by peroyvind** [yaourdt/mgos-to-tasmota#6]
Hi.

I've been trying to flash a couple of Shelly 1, but no success so far.

I tried two different shelly's, and both were newest firmware available. I can see the JSON output as expected, and the shelly restarts one time (i ping it all the time, so i can see that it dies one time) but nothing more happends.

I saw a closed issue here with something similiar, so i tried to download the zip file to a local web server and changed the URL so that the shelly would download it from there. Then the Shelly restarted one time, and i can ping it, but the shelly web server is now not accessible. Since i downt have a cable here right now i dont want to try that with the second one yet 😄 

Any suggestions?

**Comment by yaourdt** [comment]
Hm, is your Shelly able to access the internet? 

The firmware download is a two-step procedure: First, the Shelly downloads the intermediate mg2tasmota firmware from `http://dl.dasker.eu`. Without access to the internet, this step will normally fail. You avoided this by hosting it on a local web server and as far as I can tell managed to install the intermediate firmware.

Now, the second step is the intermediate firmware connecting to the last used WiFi network and to download tasmota from `https://raw.githubusercontent.com`. If you can ping it, it is connected to the WiFi and you are almost there. As soon as the device is able to connect to the internet (please do check you router settings), restart it by unplugging it, and it will download tasmota and flash as expected.
